# This workflow will install Python dependencies, run tests

name: GitHub Actions Parallel Run of Inventory tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Inventory-Application-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest inventory_application -s -v --durations=0 --cov=.
  Inventory-Application-Store-Multiple-Items-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest inventory_application_store_multiple_items -s -v --durations=0 --cov=.
  Inventory-Application-Deep-Dive-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest inventory_application_deep_dive -s -v --durations=0 --cov=.